### ISSUE TITLE
DOMException: The operation is insecure

### ISSUE THREAD

**Issue by Orangian** [revoltchat/self-hosted#10]
Just self hosted an instance, but I can't login after onboarding as the firefox console always spits out:
```
DOMException: The operation is insecure. util.tsx:21:16
    Ot util.tsx:21
    o Form.tsx:69
    onSubmit Form.tsx:107
    ie index.esm.js:1099
    Preact 31
        k
        (Async: EventListener.handleEvent)
    E
        __e
        __e
        T
        O
        __e
        T
        O
        T
        O
        T
        O
        T
        O
        T
        O
        T
        O
        T
        O
        T
        O
        __e
        T
        O
        __e
        T
        O
        __e
        T
```
Now, I have no clue what this means, can anyone help?

**Comment by Orangian** [comment]
Possibly similar to livewire/livewire#1529, could be an issue with the fact that the Revolt server is running on HTTP but being proxied as HTTPS. In that case, is there anything I can do to fix this, or is this an issue on Revolt's end?

**Comment by roobre** [comment]
It might be possible that you changed all URLs in the config file from `http` to `https` but, like me, forgot to change the websocket schema from `ws` to `wss`. That fixed the error for me :)

**Comment by Orangian** [comment]
That fixed it, thanks! (As far as I can tell, mongo is refusing to work right now, but I'd expect to get that error beforehand.)
