### ISSUE TITLE
Bug: Issue with file uploads

### ISSUE THREAD

**Issue by mirkohubtv** [revoltchat/self-hosted#101]
### What happened?

Hi there,

I’m trying to self-host Revolt following the official repository on my Windows 11 machine with Docker.

Everything is working fine except for the file uploads (Autumn endpoint). I’ve followed the guide step by step and tried multiple solutions, but after hours of debugging, I still can’t figure out what’s causing the issue.

If anyone has experience with this or can point me in the right direction, I’d greatly appreciate it. I’ve been stuck for quite some time, and I’m running out of ideas. I’m also open to a Discord or Revolt call if that makes troubleshooting easier.

Thanks in advance for any help!

![image](https://github.com/user-attachments/assets/0c5c1a65-b5a1-4c2a-ab68-fbeed2189377)
![image](https://github.com/user-attachments/assets/4552594c-0613-4673-b7c4-ca3f7891a912)

**Comment by FifthSparrow** [comment]
I am also getting this same issue (except with a status error of 500) with `autumn:1.1.11` on a fresh install. 

Unrelated to this error, but  `files.s3.default_bucket` in Revolt.toml should probably be renamed from "revolt-uploads" to "attachments". And the caddyfile should use port 3000 instead of 14704 for `autumn:1.1.11`.  It seems that the latest container images for autumn after 1.1.11 are now using port 14704, but they seem to error out for me when I try to docker run them.

**Comment by FifthSparrow** [comment]
> I solved my issue by running autumn in a separate instance, you may try it. We need to wait a fix.

Do you mean running autumn as a separate docker container outside the docker compose.yaml file? Could you please share how you configured that?

**Comment by FifthSparrow** [comment]
> > > I solved my issue by running autumn in a separate instance, you may try it. We need to wait a fix.
> > 
> > 
> > Do you mean running autumn as a separate docker container outside the docker compose.yaml file? Could you please share how you configured that?
> 
> Sure.
> 
> git clone https://github.com/revoltchat/autumn.git autumn
> cd autumn
> cargo build
> export AUTUMN_HOST="0.0.0.0:8081"
> export AUTUMN_MONGO_URI="YOUR_MONGODB_URI"
> cargo run
> You may proxy via nginx the port 8081 like `autumn.example.com` and configurate it on Revolt .env/.toml files
> 
> AUTUMN_PUBLIC_URL=https://autumn.example.com
> And that's it. You now can upload files. If you need more help with setup feel free to contact me on Revolt `MirkoHubTV#8516` or Discord: `mirkohubtv`.

@mirkohubtv Thank you! That worked. For anyone who wants to do that using docker:
```
docker run -it --name autumn_container \
  -p 3000:3000 \
  -v autumn_data:/data \
  -e AUTUMN_HOST="0.0.0.0:3000" \
  -e AUTUMN_MONGO_URI="YOUR_MONGODB_URI" \
  rust:latest /bin/sh -c "
    apt-get update -y && apt-get upgrade -y && apt-get install -y git pkg-config libssl-dev && \
    git clone https://github.com/revoltchat/autumn.git /autumn && \
    cd /autumn && \
    cargo build --release && \
    cargo run --release
  "
```

**Comment by JoCat** [comment]
Changing the port for autumn in Caddyfile helped me

**Comment by kotazzz** [comment]
> Changing the port for autumn to 3000 in Caddyfile worked for me

Me too. Thank you for help
