### ISSUE TITLE
bug: after registration, there is no way to log in to the app

### ISSUE THREAD

**Issue by xpamych** [revoltchat/self-hosted#108]
### What happened?

![Image](https://github.com/user-attachments/assets/6bd2cc7c-cb57-457e-b23b-d4ab8d91d381)
![Image](https://github.com/user-attachments/assets/217d886a-0eb5-4ff2-8e1c-5197d0eaa5ef)
![Image](https://github.com/user-attachments/assets/61bf7cff-3e9c-41f5-baf4-e8939b6bd8fa)
![Image](https://github.com/user-attachments/assets/1dcfc6d8-202f-4bfe-877a-6c9802e07d11)

if update page

![Image](https://github.com/user-attachments/assets/9f9535da-b479-462a-9c8f-16a882b372fe)

![Image](https://github.com/user-attachments/assets/c886ab46-0cf3-417b-8f3d-7e8fe82cf581)

**Comment by Re3os** [comment]
@xpamych Ну и где же полный лог? Вангую проблема связана с reddis.
