### ISSUE TITLE
config not honoring WS port

### ISSUE THREAD

**Issue by roachadam** [revoltchat/self-hosted#22]
**Description**:
Changing the port for the websocket in .env file does not honor the new port.
Changing WS port to 9001 does not start the websocket on port 9001, but instead 9000.

**Specs**:
Centos 7 64bit

**Pics**:
Revolt attempts to request WS at correct addr/por
![image](https://user-images.githubusercontent.com/30098945/144734276-c4cb4e60-a079-42aa-9e9f-8c990a31f644.png)

**Comment by Zomatree** [comment]
Changing the environment variables will change the websocket host, make sure its running with the most up to date version of the env file.

**Comment by roachadam** [comment]
It should have been. I edited the env back to port 9000 and it is working fine. Changing back to 9001 after restarting docker produces the same error.

**Comment by insertish** [comment]
You have to change the port in `docker-compose.yml` as well.
The `.env` file is solely used by the API server to tell the client where it needs to connect.
