### ISSUE TITLE
Blank screen on Quick Start

### ISSUE THREAD

**Issue by Codeize** [revoltchat/self-hosted#26]
So while running the Quick Start portion of the self-hosted guide it works fine, docker does its thing, no errors whatsoever.

When I try visit http://local.revolt.chat:5000/ I get a blank grey screen

In the console, it shows the following

![image](https://user-images.githubusercontent.com/63158950/147497082-309bc7e9-abf8-4177-8eb9-8dab6545ed23.png)

--

In the Docker logs it seems to be working fine

![image](https://user-images.githubusercontent.com/63158950/147497153-e9914685-3095-4950-98ac-e247c619e554.png)

I have made no changes to the .env file whatsoever, just cloned this repo and tried to run it, any help would be appreciated.

**Comment by Multigestern** [comment]
same here

**Comment by Codeize** [comment]
@insertish Do you have any idea what the cause is for this?

**Comment by insertish** [comment]
I would probably need additional context, cannot reproduce. Is there any specific error on the page or..?

**Comment by Codeize** [comment]
After some additional testing, it throws the
```
ERR_CONTENT_DECODING_FAILED
```
error when I try visit the site.

Not sure what else would be of use, if you have anything else you wish me to provide let me know.

**Comment by insertish** [comment]
Pull latest images, `docker-compose pull`.

**Comment by Multigestern** [comment]
[17:19:11] 200 ─ 1.37ms ─ /assets/logo_round.png
  [17:19:11] 200 ─ 97.75ms ─ /assets/vendor.6e614c2e.js
  [17:19:11] 200 ─ 4.78ms ─ /assets/main.4be84a06.css
  [17:19:11] 200 ─ 5.45ms ─ /assets/Radio.6ca1c6b0.js
  [17:19:11] 200 ─ 4.35ms ─ /assets/Radio.db38cba2.css
  [17:19:11] 200 ─ 3.37ms ─ /assets/main.edb798bf.js
  [17:19:10] 200 ─ 1.48ms ─ /
  
  sadly still the same.

**Comment by Codeize** [comment]
> Pull latest images, docker-compose pull.
This resolved it for me. Thank you very much insert.
