### ISSUE TITLE
Refused to frame

### ISSUE THREAD

**Issue by SurpriseLon** [revoltchat/self-hosted#31]
Refused to frame 'https://rvlt.gg/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://*.revolt.chat http://local.revolt.chat:3000".

**Comment by Zomatree** [comment]
selfhosted instances don't have access to the discovery.

**Comment by SurpriseLon** [comment]
OK,then how to import external bots?I think self-hosting websites need a discover page.

**Comment by Zomatree** [comment]
The Discover page is closed source and not open for self-hosted instances. If you want to a bot running on your self-hosted instance, the bot needs to connect to your instance.

**Comment by insertish** [comment]
> OK,then how to import external bots?I think self-hosting websites need a discover page.

Just a note, those bots can't just be "imported" so to speak, they would have to be hosted by you or someone else on this separate instance. When it comes to closed source bots, you're out of luck regardless.

Closing issue.
