### ISSUE TITLE
Setup Nginx reverse proxy

### ISSUE THREAD

**Issue by clemone210** [revoltchat/self-hosted#33]
Did anyone sucessfully got revolt working behind nginx reverse proxy?
I tried a couple of things, but it exceeds my knowledge.

Would appreatiate a working config.

**Comment by insertish** [comment]
In an effort to clean up the global issue tracker, I'm currently consolidating all issues regarding self-hosting into https://github.com/revoltchat/vortex/issues/23#issuecomment-1113594595.
