### ISSUE TITLE
S3 ERROR

### ISSUE THREAD

**Issue by 547555909** [revoltchat/self-hosted#38]
I'm using the latest compose,and when i upload new avatars,it still have s3 error
S3 buckets setting:

# S3 Region
AUTUMN_S3_REGION=minio

# S3 Endpoint
AUTUMN_S3_ENDPOINT=http://minio:9000

# MinIO Root User
MINIO_ROOT_USER=minioautumn

# MinIO Root Password
MINIO_ROOT_PASSWORD=minioautumn

**Comment by 547555909** [comment]
solved

**Comment by joeBwanKenobi** [comment]
What did you do to resolve this? Currently experiencing the same issue.
