### ISSUE TITLE
Is any Android client support self-hosted server

### ISSUE THREAD

**Issue by 547555909** [revoltchat/self-hosted#39]
Is any Android client support self-hosted server?

**Comment by nagyrobi** [comment]
Yes, how to configure the Android client to work with the self-hosted server?

**Comment by sergiorgb** [comment]
You need a custom kernel with cgroups support first, once you have that you may use a chroot with a util like linux deploy and install the docker there

**Comment by insertish** [comment]
The Android client is simply a wrapper around the web app, you'll need to compile your own using something like bubblewrap-cli.
