### ISSUE TITLE
NETWORK ERROR on registration

### ISSUE THREAD

**Issue by prp-e** [revoltchat/self-hosted#41]
Greetings. 

I have a Debian virtual machine (VirtualBox on my Macbook) and I run `docker-compose` on it. I just followed the README instructions and then, I went to my browser and went to `localhost:5000`. Revolt's index page appeared, but when I tried to just register a new account, I got a network error.

**Comment by josealonso** [comment]
> Greetings.
> 
> I have a Debian virtual machine (VirtualBox on my Macbook) and I run `docker-compose` on it. I just followed the README instructions and then, I went to my browser and went to `localhost:5000`. Revolt's index page appeared, but when I tried to just register a new account, I got a network error.

Go through this "guide" ---> https://github.com/revoltchat/self-hosted/issues/25

**Comment by insertish** [comment]
In an effort to clean up the global issue tracker, I'm currently consolidating all issues regarding self-hosting into https://github.com/revoltchat/self-hosted/issues/25#issuecomment-1113606628.
