### ISSUE TITLE
How to ban someone on the network?

### ISSUE THREAD

**Issue by Cocam123** [revoltchat/self-hosted#42]
Hello,

I don't know if I should put this here or in a request but I would like to know how to ban a user from our Revolt server

(for the moment there is nobody who has violated the conditions, the thing is that we try to keep a safe place for everybody)

So I would like to know how it works on this exactly

**Comment by insertish** [comment]
For now, you'll have to [jump into the database](https://github.com/revoltchat/self-hosted#expose-database) and manually wipe them. Admin panel may be built at some point but it's not currently a priority.
