### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 ()

### ISSUE THREAD

**Issue by Drakenasa** [revoltchat/self-hosted#45]
Hey everyone, I've see no mention of it here, but I've noticed that I can't add a banner to any given Revolt server. Doing so results in a popup stating "An error occurred! See console", and the console reveals the following: 
`Failed to load resource: the server responded with a status of 400 ()  [https://vite.natrana.com/servers/01G2FJ6NJPCFTCGB1JGCG1WX77]`

Is this a known issue? Any suggestions? 

Thank you!

**Comment by insertish** [comment]
This was fixed in https://github.com/revoltchat/backend/commit/dc6ce96aa2582c775b5cf20819c79b4471670003.
