### ISSUE TITLE
bug: errors in my redirection

### ISSUE THREAD

**Issue by cjeje84** [revoltchat/self-hosted#46]
### What happened?

I have errors in my redirection here is a screen
![image](http://newdream.ml:3000/attachments/D5FdlmY167LomQrjWO3PGfFMRLhMw5h30KVZmrua04/image.png)

![image](https://user-images.githubusercontent.com/18289153/169754969-fffbc151-a890-42c3-8c98-b5bdf25bceb3.png)

**Comment by insertish** [comment]
Banner upload was fixed in https://github.com/revoltchat/backend/commit/dc6ce96aa2582c775b5cf20819c79b4471670003.
