### ISSUE TITLE
bug: on a clean install, api returns 401 on account login

### ISSUE THREAD

**Issue by narvikd** [revoltchat/self-hosted#48]
Hello,

The last commit (https://github.com/revoltchat/self-hosted/commit/0c08213a94c37bf1959b8ac45e00598d994aa041) introduces a bug in which if you create a new account, you cannot log in regardless of settings.

I managed to fix it reverting to: https://github.com/revoltchat/self-hosted/commit/4a0ccfb7fd49f37a342d6592fc933c03c8419d43

**Comment by insertish** [comment]
Fairly sure this currently works.
