### ISSUE TITLE
Change File upload size limit

### ISSUE THREAD

**Issue by inputoutput1126** [revoltchat/self-hosted#53]
this is less of an issue and more of a question that I can't find the answer to. My main reason for wanting to self-host revolt is to provide an experience similar to discord without an upload limit. I've successfully gotten it running locally but I cannot find where in the configuration files I can change the max upload size.

**Comment by Zomatree** [comment]
Upload limits are controlled via the `Autumn.toml` file, https://github.com/revoltchat/autumn/blob/master/Autumn.toml

**Comment by inputoutput1126** [comment]
How would I be able to access that file if I have it installed w/ docker? I'm not well versed w/ docker at all

**Comment by demetera** [comment]
> How would I be able to access that file if I have it installed w/ docker? I'm not well versed w/ docker at all

1) Check docker containers with : `docker ps -a`
2) Identify ID of Autumn container
3) "Login" to container with : `docker exec -u 0 -it <Container ID> /bin/bash`
4) Install vim or nano with : `apt install`
5) Modify and save `Autumn.toml` file

**Comment by insertish** [comment]
Closing as solved for now.
Though you should mount `Autumn.toml` into the container instead.

**Comment by mlyasota** [comment]
Editing line 10 in Autumn.toml with nano or mounting into the container does not change the file upload limits.

**Comment by shlomi8801-2** [comment]
> > How would I be able to access that file if I have it installed w/ docker? I'm not well versed w/ docker at all
> 
> 1. Check docker containers with : `docker ps -a`
> 2. Identify ID of Autumn container
> 3. "Login" to container with : `docker exec -u 0 -it <Container ID> /bin/bash`
> 4. Install vim or nano with : `apt install`
> 5. Modify and save `Autumn.toml` file

this doesnt work anymore i tried adding this to the docker compose file and adding an Autumn.toml file to the current dir but it didnt do nothing special

<img width="564" height="301" alt="Image" src="https://github.com/user-attachments/assets/41ed0877-0c9e-4fd7-ba62-1e52a5c92872" />
