### ISSUE TITLE
Stack Network error

### ISSUE THREAD

**Issue by dlartigu** [revoltchat/self-hosted#54]
### What happened?

Hello, I've managed to build a stack based on the self hosted revolt chat docker (https://github.com/revoltchat/self-hosted)
It's working... but as I'm already using portainer and traefik the ports are not working. - Getting Network Error when I try to subscribe -

Any idea on how to fix that ? And maybe it can help others too :)
I mean I already have a: portainer + swarmpit + traefik  + gitea + drone + taiga
When I try to subscribe it's says Network error.

Thanks

version: '3.8'

x-default: &defaults
  environment:
   - MONGODB=mongodb://database
   - REDIS_URI=redis://redis/
   - REVOLT_APP_URL=http://revolt.PRIVATE
   - REVOLT_PUBLIC_URL=http://revolt.PRIVATE
   - VITE_API_URL=http://revolt.PRIVATE
   - REVOLT_EXTERNAL_WS_URL=ws://revolt.PRIVATE
   - AUTUMN_PUBLIC_URL=http://revolt.PRIVATE
   - JANUARY_PUBLIC_URL=http://revolt.PRIVATE
   - REVOLT_UNSAFE_NO_CAPTCHA=1
   - REVOLT_UNSAFE_NO_EMAIL=1
   - REVOLT_INVITE_ONLY=0
   - REVOLT_MAX_GROUP_SIZE=150
   - REVOLT_VAPID_PRIVATE_KEY=LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUJSUWpyTWxLRnBiVWhsUHpUbERvcEliYk1yeVNrNXpKYzVYVzIxSjJDS3hvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWnkrQkg2TGJQZ2hEa3pEempXOG0rUXVPM3pCajRXT1phdkR6ZU00c0pqbmFwd1psTFE0WAp1ZDh2TzVodU94QWhMQlU3WWRldVovWHlBdFpWZmNyQi9BPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
   - REVOLT_VAPID_PUBLIC_KEY=BGcvgR-i2z4IQ5Mw841vJvkLjt8wY-FjmWrw83jOLCY52qcGZS0OF7nfLzuYbjsQISwVO2HXrmf18gLWVX3Kwfw=
   - AUTUMN_S3_REGION=minio
   - AUTUMN_S3_ENDPOINT=http://minio:9000
   - MINIO_ROOT_USER=minioautumn
   - MINIO_ROOT_PASSWORD=minioautumn
   - AWS_ACCESS_KEY_ID=minioautumn
   - AWS_SECRET_ACCESS_KEY=minioautumn

networks:
  traefik-public:
    external: true

services:
  # MongoDB database
  database:
    <<: *defaults
    image: mongo
    volumes:
      - revoltdb:/data/db
    networks:
      - traefik-public

  # Redis server
  redis:
    <<: *defaults
    image: eqalpha/keydb
    networks:
      - traefik-public

  # API server (delta)
  api:
    <<: *defaults
    image: ghcr.io/revoltchat/server:20220715-1
    depends_on:
      - database
      - redis
    ports:
      - "8000:8000"
    networks:
      - traefik-public

  # Events service (quark)
  events:
    <<: *defaults
    image: ghcr.io/revoltchat/bonfire:20220715-1
    depends_on:
      - database
      - redis
    ports:
      - "9000:9000"
    networks:
      - traefik-public

  # Web App (revite)
  web:
    <<: *defaults
    image: ghcr.io/revoltchat/client:master
    ports:
      - "5000:5000"
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.revolt-http.rule=Host(`revolt.PRIVATE`)
        - traefik.http.routers.revolt-http.entrypoints=http
        - traefik.http.routers.revolt-http.middlewares=https-redirect
        - traefik.http.routers.revolt-https.rule=Host(`revolt.PRIVATE`)
        - traefik.http.routers.revolt-https.entrypoints=https
        - traefik.http.routers.revolt-https.tls=true
        - traefik.http.routers.revolt-https.tls.certresolver=le
        - traefik.http.services.revolt.loadbalancer.server.port=5000

  # S3-compatible storage server
  minio:
    <<: *defaults
    image: minio/minio
    command: server /data
    volumes:
      - revoltminio:/data
    ports:
      - "10000:9000"
    networks:
      - traefik-public

  # Create buckets for minio.
  createbuckets:
    <<: *defaults
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      while ! curl -s --output /dev/null --connect-timeout 1 http://minio:9000; do echo 'Waiting minio...' && sleep 0.1; done;
      /usr/bin/mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb minio/attachments;
      /usr/bin/mc mb minio/avatars;
      /usr/bin/mc mb minio/backgrounds;
      /usr/bin/mc mb minio/icons;
      /usr/bin/mc mb minio/banners;
      /usr/bin/mc mb minio/emojis;
      exit 0;
      "

  # File server (autumn)
  autumn:
    <<: *defaults
    image: ghcr.io/revoltchat/autumn:1.1.5
    depends_on:
      - database
      - createbuckets
    environment:
      - AUTUMN_MONGO_URI=mongodb://database
    ports:
      - "3000:3000"
    networks:
      - traefik-public

  # Metadata and image proxy (january)
  january:
    <<: *defaults
    image: ghcr.io/revoltchat/january:master
    ports:
      - "7000:7000"
    networks:
      - traefik-public

volumes:
  revoltdb:
  revoltminio:

**Comment by insertish** [comment]
Not enough information to work with.
If you want support with self hosting please use Revolt Lounge (https://rvlt.gg/Testers) instead of issues.
