### ISSUE TITLE
bug: Unable to verify the email address of new accounts

### ISSUE THREAD

**Issue by Cocam123** [revoltchat/self-hosted#55]
### What happened?

Since I updated Revolt with the latest update and then changed my domain name (by changing it in the config file), it is impossible to check the emails of the new accounts. I have temporarily disabled this feature until a fix is found here or by me and my staff
![image (1)](https://user-images.githubusercontent.com/64326243/202786333-4076552f-575c-4bc2-84d9-a49e0fffd79d.png)

**Comment by Cocam123** [comment]
I don't know if this can help you too
![Capture2](https://user-images.githubusercontent.com/64326243/202793455-741b48a4-8a3b-430d-81ee-ce22ec082420.png)
![Capture3](https://user-images.githubusercontent.com/64326243/202793457-36628c2e-7d1d-43a8-a5e7-b19cc5cb6da8.png)
![Capture1](https://user-images.githubusercontent.com/64326243/202793458-dfb01c86-79f9-47ae-b90d-4cd3f9badf8d.png)

**Comment by Cocam123** [comment]
[UPDATE]

I noticed that when I create a new invitation, it is sent with the old domain name. The thing is that I changed the domain name in the .env file (the REVOLT_APP_URL line is on the new domain name while the application always returns the old domain name).

I would like to know how to change it because the application seems to return the old domain name every time despite the fact that the .env file is up to date

**Comment by insertish** [comment]
Can't tell what the issue is at a glance, if you still have issues please use Revolt Lounge (https://rvlt.gg/Testers) for support not the issues here.
