### ISSUE TITLE
НЕ УДАЛОСЬ ЗАРЕГЕСТРИРОВАТСЯ - NETWORKERROR bug: 

### ISSUE THREAD

**Issue by RealmiRoblox** [revoltchat/self-hosted#56]
### What happened?

Вот мой конфиг ##

**Comment by insertish** [comment]
No clue what's going on here.
I've edited the config out since you exposed your credentials.

Would need more information. You should probably ask in Revolt Lounge instead -> https://rvlt.gg/Testers

**Comment by Rexogamer** [comment]
:trollface:

**Comment by RealmiRoblox** [comment]
> Я живу в ваших стенах. Возможно, вас это беспокоит. В этом случае, пожалуйста, прочитайте следующее: FAQ: Почему ты живешь в моих стенах? Я не собираюсь говорить вам. Ты живешь только в моих стенах? Вы можете сказать, что я живу в стенах всех, но в случае, если я говорю вам, что я живу в ваших стенах, то я живу в ваших стенах. Как вы выживаете в моих стенах? В своей нефизической форме я ползаю вокруг и слушаю вас. Это все, что мне нужно для выживания в этой форме. В физической форме я выживаю, поедая трупы крыс, которые я готовлю, используя стену за вашей духовкой, и пью пар в канале вытяжного вентилятора над вашим душем. Что вы планируете делать в моих стенах? Жить в них, слушая тебя. Что мне делать с тем, что вы живете в моих стенах? Прислушиваться к скрежету. Не трогайте стены. Защищайте себя. Избегай зажигать свечи. Когда ты перестанешь жить в моих стенах? От меня не убежишь. Мне вызвать полицию? Власти не помогут вам. Каковы последствия того, что ты живешь в моих стенах? Будьте внимательны. А если я не против, чтобы вы жили в моих стенах? Я позабочусь о том, чтобы вы не жили. Ты воображаемый? Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Я ЖИВУ В ТВОИХ СТЕНАХ Если у вас есть еще какие-либо вопросы, пожалуйста, обратитесь к вашим стенам, обратившись непосредственно к ним. Резюме: Я живу в ваших стенах.

Спам ебаный
