### ISSUE TITLE
bug: Network Error Upon Registration or Log In

### ISSUE THREAD

**Issue by ghost** [revoltchat/self-hosted#57]
### What happened?

I am having issue where I am given a network error in the client when i try to sign in or make an account. I have followed whatever little documentation there is, but I cannot get rid of this error. I have tried with the server being pointed locally and exposed to the internet, with all specified ports open in my firewall; -still nothing.

**Comment by Rexogamer** [comment]
> creates issue
> deletes account no longer than an hour later

**Comment by insertish** [comment]
Closing issue due to missing author.
