### ISSUE TITLE
Local offline dev spinup not working

### ISSUE THREAD

**Issue by onsettech** [revoltchat/self-hosted#58]
### What do you want to see?

Hello all,
Trying to setup revolt chat for local development on Ubuntu, it installs correctly, both on the dev version of revolt chat and the self-hosted version, however as soon as I go offline, it says an error has occurred.

I changed the ip's in the .env file for 127.0.0.1 and also tried local host, still no success.

Is there a way to develop offline? On a local spin up?

Note: I installed and compiled everything online then switched to offline to test.

**Comment by Rexogamer** [comment]
What error are you getting?

**Comment by onsettech** [comment]
"An error occurred" popup window on window refresh

**Comment by onsettech** [comment]
In the browser console it says "State must be Ready in order to transition! (currently Offline)".
Does this mean that there are required online deps?

**Comment by onsettech** [comment]
![Image](https://user-images.githubusercontent.com/82743150/216439419-e05a5d92-a4b4-4d97-8da1-8245736b59f8.png)

**Comment by onsettech** [comment]
![Image](https://user-images.githubusercontent.com/82743150/216439553-6bfd7ece-9d51-4db3-a7c0-7e3e017a8f47.png)

**Comment by insertish** [comment]
This isn't intended for development, you may want to look at https://developers.revolt.chat/contributing.
If you still want to run this in particular, please read https://github.com/revoltchat/self-hosted/issues/59.
