### ISSUE TITLE
❗ Self-Hosting Support

### ISSUE THREAD

**Issue by insertish** [revoltchat/self-hosted#59]
If you want to get support with running Revolt, please use the #Programming channel on the [Revolt Lounge server](https://rvlt.gg/Testers).

Somebody from the team may help you if they are available, but please do not mention anyone in particular for help as Revolt is pretty much entirely volunteer supported and nobody has an obligation to help you for free.

**Comment by AToska21** [comment]
how do you add badges, i have compass open but i'm a bit confused on how to do it

**Comment by insertish** [comment]
No longer relevant due to changes on server.
