### ISSUE TITLE
feature request: screenshare

### ISSUE THREAD

**Issue by wendellmeset** [revoltchat/self-hosted#60]
### What do you want to see?

Full screenshare support, and possibly built in remote desktop

**Comment by Hidend** [comment]
this is for self host issues, not feature requests.
Make your feature request here: https://github.com/orgs/revoltchat/discussions/categories/feature-suggestions?discussions_q=is%3Aopen+category%3A%22Feature+Suggestions%22

**Comment by Rexogamer** [comment]
(This is also a duplicate issue; see the Vortex repo)
