### ISSUE TITLE
feature request: 32bit support

### ISSUE THREAD

**Issue by markweenwork** [revoltchat/self-hosted#65]
### What do you want to see?

any chance we can get self-hosting to work on i386 processors?
I have a low powered atom processor that is 32bit that i would like to use for hosting a revolt server

thanks

**Comment by insertish** [comment]
The main two markets are amd64 and arm64 currently, unless if more demand somehow crops up for 32-bit, I don't think this is sensible to implement as it would significantly increase build times again.

**Comment by insertish** [comment]
Haven't seen any requests for support, I am going to close this out.
