### ISSUE TITLE
unknown error bug: 

### ISSUE THREAD

**Issue by killforby** [revoltchat/self-hosted#66]
### What happened?

Hello, it is impossible for me to install self-hosted revolt I still have an error when registering? Any idea?

![image](https://github.com/revoltchat/self-hosted/assets/94224508/bceb3d08-8568-4ee1-8c6b-5b45b2e3c438)

**Comment by softweed** [comment]
Hello,

Having the same problem :/

**Comment by jrmiller82** [comment]
Same here; same problem here. The documentation needs a large rework, particularly for setting up reverse proxies.

**Comment by mstrgh** [comment]
Hey, is everything set-up correctly in your .env and docker-compose.yml files?

**Comment by jrmiller82** [comment]
I followed the documentation, so if there's a problem it's on the documentation side. I think one of the admins should try getting the container running from scratch and see if they don't run into any issues / update the documentation.

**Comment by mstrgh** [comment]
> I followed the documentation, so if there's a problem it's on the documentation side. I think one of the admins should try getting the container running from scratch and see if they don't run into any issues / update the documentation.

try'd to, runs without any issues, maybe try messing around a bit and see if it works for example on an local ip

**Comment by CresentMoon** [comment]
80 port is banned herer, so I had to set the entrance to 5010, but it shows  an network error when registering.

Here is the configuration and the rest is just same as the guide page.

.env
```##
## Quark configuration
##

# MongoDB
MONGODB=mongodb://database

# Redis
REDIS_URI=redis://redis/

# Hostname used for Caddy
# This should in most cases match REVOLT_APP_URL
HOSTNAME=:80

# URL to where the Revolt app is publicly accessible
REVOLT_APP_URL=http://replaceblock.myqnapcloud

# URL to where the API is publicly accessible
REVOLT_PUBLIC_URL=http://replaceblock.myqnapcloud/api
VITE_API_URL=http://replaceblock.myqnapcloud/api

# URL to where the WebSocket server is publicly accessible
REVOLT_EXTERNAL_WS_URL=ws://replaceblock.myqnapcloud/ws

# URL to where Autumn is publicly available
AUTUMN_PUBLIC_URL=http://replaceblock.myqnapcloud/autumn

# URL to where January is publicly available
JANUARY_PUBLIC_URL=http://replaceblock.myqnapcloud/january


##
## hCaptcha Settings
##```

docker-compose.yml

```# Caddy web server
  caddy:
    image: caddy
    restart: always
    env_file: .env
    ports:
      - "5010:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
 ```

**Comment by softweed** [comment]
Okay I got it to work. revolt-database doesn't support the processor type kvm64, switched it to host and this solved my problem. Hope that helps someone

**Comment by insertish** [comment]
Documentation has been updated, please feedback if any issues persist.
