### ISSUE TITLE
bug: Unable to friend or direct message users due to missing discriminator

### ISSUE THREAD

**Issue by GanimanSwift** [revoltchat/self-hosted#68]
### What happened?

On a fresh self-hosted instance, it is not possible to send friend requests, accept friend requests or direct message users. This seems to be caused by the client not having values for user # discriminators. In all places I can see a username, the discriminator numbers are missing or null, so usernames appear as: `Ganiman#` or `Ganiman#undefined`.

![revolt_discriminator_missing](https://github.com/revoltchat/self-hosted/assets/13344227/adc9e0b6-4003-4e33-a5cb-3e1a8665c990)

**Comment by GanimanSwift** [comment]
It looks like https://github.com/revoltchat/self-hosted/pull/67 addresses this issue.

**Comment by insertish** [comment]
Closed in aa3a3e3a7e232a9ac2520b338d44f847a8b52e76
