### ISSUE TITLE
bug: Network error

### ISSUE THREAD

**Issue by Xcalivyr** [revoltchat/self-hosted#70]
### What happened?

Every time I've tried installing the AppImage and running it through AppImageLauncher (and yes, I did set it as executable prior) the application just sends me this:
![image](https://github.com/revoltchat/self-hosted/assets/34685707/1a47f8d5-64e2-48c3-ac62-69b2bd90ad21)
I've tried reloading and restarting the app, both directly and through the terminal, to no avail; and removing and reinstalling the file to start over again hasn't made a difference either. The Web App seems to have a similar issue: every time I try to log in and enter my authenticator key, it shows the same thing there. Is there an issue with the app itself, or is it on my end?

**Comment by Xcalivyr** [comment]
I should add the Web App version actually shows me this:
![image](https://github.com/revoltchat/self-hosted/assets/34685707/4da84e5e-f18b-4ac7-89e0-3af524a73356)
Even reloading and signing in again takes me back here.

**Comment by insertish** [comment]
Probably momentary failure at time of issue creation, closing out since issue went stale.
