### ISSUE TITLE
bug: serving pterodactyl behind reverse proxy causes DOMException: The operation is insecure.

### ISSUE THREAD

**Issue by KenwoodFox** [revoltchat/self-hosted#71]
### What happened?

I am getting an issue really similar to https://github.com/revoltchat/self-hosted/issues/10 , when loading a web page, I cant control or really.. do anything, server controls don't work and I get the `The operation is insecure.` error.

I think its because I'm hosting the pterodactyl server over HTTP, and then proxying it + adding my SSL cert afterward. I looked around, and the cause makes sense. because I actually am hosting the server over HTTP, it confuses the server and doesn't accept URLs beginning with https?

I'm thinking maybe I'll self sign some certs and just host it over https internally? it sounds kinda silly but i could do that? Is there an easier way? a config setting for when you're using a reverse proxy?

let me know if there is any more info i can provide.

**Comment by KenwoodFox** [comment]
Ah... using chrome produces some more helpful debug.
![image](https://github.com/revoltchat/self-hosted/assets/31870999/0ade6414-c2a9-4f2b-9f1f-5544cafef767)
that IP, 10.85.3.103 is the direct connection to the wing. It cant do that, I'm surprised. I had thought I had forbidden that path.

Is this how pterodactyl works? Do I need to make my wings accessible externally too? that would certainly make it more involved for me to provide a subdomain for every wing..

**Comment by KenwoodFox** [comment]
Behind proxy is set... but still same error? im struggling to setup a self-signed cert haha.. this is why i centralize all my certs on my reverse proxy in the first place, https://pterodox.com/guides/reverse-proxy.html#for-wings

**Comment by insertish** [comment]
Sir, this is Revolt

Closing out for unrelated issue
