### ISSUE TITLE
bug: in Debian Bullseye VM in docker january says 'GLIBC_2.29 not found required by ./january'

### ISSUE THREAD

**Issue by accessiblepixel** [revoltchat/self-hosted#72]
### What happened?

Expected all containers to launch after following instructions from self-hosted repo.

I am running a Debian Bullseye VM in KVM/QEMU with CPU type 'max' (for x86x64_v2 support which appears required by the application). The rest of the containers launch successfully but the january container doesn't launch. Getting the logs it says:
./january: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.29' not found (required by ./january)
./january: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ./january)

VM Info:
2 vCPU (Set to type 'max')
2GB RAM
32GB Disk

OS: Debian Version 11.8

Docker Info:
Docker Version: 20.10.5+dsfg1, build 55c4c88
Docker-Compose version: 1.25.0

Please let me know if you need me to provide anything else, and if I have posted this in the wrong place I'm still getting accustomed to github. <3

Any pointers would be appreciated.

**Comment by typicalaimster** [comment]
Looks like editing the docker-compose file and pulling the tag january:0.3.5 worked for me. Something is up with January's master build.

**Comment by 4kh00** [comment]
On my local machine, this bug is happening. @typicalaimster's solution works with no side effects afaik.

**Comment by prologic** [comment]
This is fixed by https://github.com/revoltchat/january/pull/39

**Comment by accessiblepixel** [comment]
Awesome! Well feel free to close the issue once the pull has been reviewed/accepted (I think that's the right terminology) :)

Haven't had chance to test myself, but everyone's help has been appreciated and glad you were able to work it out ❤️

**Comment by insertish** [comment]
Fixed in build `january:0.3.5-2`, also matches `:master` and `:latest` tags so you can just pull it.
