### ISSUE TITLE
feature request: Add server minimum specifications

### ISSUE THREAD

**Issue by ghost** [revoltchat/self-hosted#75]
### What do you want to see?

Hi! I love this open-source self-hostable chat, but I was wondering what the minimum server requirements are to deploy this server. Thank you! I am using an e2-micro GCP instance (since I want to do this for free), but Revolt server hosting fails. Thank you.

**Comment by AndresDevvv** [comment]
☠️

**Comment by nosiuodkrywca** [comment]
...isn't e2-micro barely enough to run bash?

**Comment by AndresDevvv** [comment]
lol

**Comment by phanomgames** [comment]
someone said 2gb of ram, and 10gb of storage. Best guess we've got.

**Comment by AndresDevvv** [comment]
nah i would say with 4 vcpus, with mine only 2gb ram and 1vcpu was lagging very laggy

**Comment by botiapa** [comment]
> ...isn't e2-micro barely enough to run bash?

Definitely not, you can easily host a vaultwarden instance for example, or any other static website (with very few traffic ofc)

**Comment by nosiuodkrywca** [comment]
> > ...isn't e2-micro barely enough to run bash?
> 
> Definitely not, you can easily host a vaultwarden instance for example, or any other static website (with very few traffic ofc)

yeah, that was just an exaggeration. it is entirely possible to run lightweight apps, but Revolt surely isn't one of them.

**Comment by tsarkovan** [comment]
Hi everybody! Do you have admin panel or somthing else for administrting revoltchat self-hosted?
