### ISSUE TITLE
bug: s3Error

### ISSUE THREAD

**Issue by KimaniLife** [revoltchat/self-hosted#76]
### What happened?

Team, 

we deployed selfhosted repo as docker and we are facing this media upload issue and erroring as s3Error and i couldn't find much logs on the same to diagnose deeper. 

can you let me know, where we are actually doing wrong? below is the .env config for our app.

##
##

# S3 Region
AUTUMN_S3_REGION=us-east-1

# S3 Endpoint
AUTUMN_S3_ENDPOINT=https://s3.us-east-1.amazonaws.com
AUTUMN_S3_BUCKET_PREFIX=kimanilifeassets-revolt
AUTUMN_LOCAL_STORAGE_PATH=./kimanilife
# MinIO Root User
MINIO_ROOT_USER=minioautumn

# MinIO Root Password
MINIO_ROOT_PASSWORD=minioautumn

# AWS Access Key ID
AWS_ACCESS_KEY_ID=********************

# AWS Secret Key
AWS_SECRET_ACCESS_KEY=**************************

**Comment by lukaslangrock** [comment]
Hi, I am also using a non-minio S3 backend with my configuration and also encounter only `S3Error` messages.
As far as I understand it, this fix is only relevant to minio-based configurations, whereas the issue actually uses AWS as the S3 backend. I fail to see how the two are connected or how that solves the issue at hand.

@KimaniLife did this actually fix your issue? If not, did you find a solution?

my `.env` for context:
```
## Configure for Backblaze B2 with S3-compatible API
AUTUMN_S3_REGION=eu-central-003
AUTUMN_S3_ENDPOINT=https://s3.eu-central-003.backblazeb2.com
AUTUMN_S3_BUCKET_PREFIX=****-revolt-

## Not using minio in this deployment
#MINIO_ROOT_USER=minioautumn
#MINIO_ROOT_PASSWORD=minioautumn

## API keys for Backblaze B2
AWS_ACCESS_KEY_ID=****
AWS_SECRET_ACCESS_KEY=****
```
*Four asterisks = redacted*

I also didn't use `createbuckets` for my deployment and made sure to create the buckets myself, using the regular names with an added prefix. For example the `attachments` bucket is named `****-revolt-attachments`.
