### ISSUE TITLE
bug: Vapid Keys guide is down

### ISSUE THREAD

**Issue by yllekz** [revoltchat/self-hosted#77]
### What happened?

```
# VAPID keys for push notifications
# Generate using this guide: https://gitlab.insrt.uk/revolt/delta/-/wikis/vapid
```

Trying to set up revolt and going through the .env file which points me to this guide. The site is unreachable?  ```Unavailable due to hardware failure, working on recovering services – Updates: https://rvlt.gg/GnFjwkqD```

I found an archive.org cached copy if needed but just FYI the prod site is down.

https://web.archive.org/web/20230612140827/https://gitlab.insrt.uk/revolt/delta/-/wikis/vapid

**Comment by Rexogamer** [comment]
Assuming the archive is up to date, this should be pretty easy to resolve - but where do we want to put the guide? This repo? The dev docs?

**Comment by dillfrescott** [comment]
Its still down?

**Comment by mpavkovic** [comment]
Because the URL is still down, and opening an archived copy takes minutes to load, I'm copy-pasting the instructions here, in case anyone needs them

> VAPID keys are used to ensure that nobody else can communicate with your clients.

> You can generate a private VAPID key by running:

```
openssl ecparam -name prime256v1 -genkey -noout -out vapid_private.pem
```

> This creates a PEM private key. In order to use this with the server, you must first base64 encode it, then you can pass it in using an environment variable. (Make sure to remove any newlines)

```
base64 vapid_private.pem
```

> To convert this to a public key, we run:

```
openssl ec -in vapid_private.pem -outform DER|tail -c 65|base64|tr '/+' '_-'|tr -d '\n'
```

> The output of this command is what the clients will be receiving.

Source: https://web.archive.org/web/20230612140827/https://gitlab.insrt.uk/revolt/delta/-/wikis/vapid

**Comment by ne275** [comment]
so why we need a vapid keys?

**Comment by insertish** [comment]
> so why we need a vapid keys?

Push notifications

**Comment by insertish** [comment]
Guide is back up, closing out issue.
Will migrate it at some point though, probably when I rewrite the documentation for the new backend stuff.
