### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by DANW999** [revoltchat/self-hosted#8]
Hi, whenever I launched Revolt using Docker Compose with the exact same template as given here, I am able to get to the login page just fine but whenever I attempt to create an account I get "FAILED TO  REGISTER - NETWORK ERROR". I have even when tested filling in the SMTP details in the env file and making sure all my ports are open as part of troubleshooting. What am I doing wrong? Thank you.

**Comment by engineeringsys** [comment]
@DANW999 Check to make sure you aren't already using any of the ports from revolt in other docker containers on your host. ie if you have Portainer running 8000/9000 may be occupied.  You can change them in the `docker-compose.yml` I just ran into this issue.

**Comment by yllekz** [comment]
Getting the same thing. Not sure why this error would fire out of the box. All ports are available.

**Comment by elightcap** [comment]
Ah. Issue for me was i didnt set a vapid key.  revoltchat/server was panicking.  After adding that, things to be mostly working as intended.

**Comment by yllekz** [comment]
I generated new keys but am still getting the network error. None of the containers/logs seem to be throwing errors either, so I'm stumped as to what's going on.

**Comment by Jimmy-SafeCash** [comment]
I have the same issue when trying to create an account. No errors in logs. (Using Traefik if that's of use).

**Comment by DANW999** [comment]
@elightcap  I am not running behind proxy and @engineeringsys I am not running on used ports (docker would provent me from spinning up the container in the first place otherwise). How would I go about generating keys? As that does not appear to be mentioned the documentation page, unless I missed it. All help is appreciated, thank you.

**Comment by engineeringsys** [comment]
@Jimmy-SafeCash Can you post your docker-compose.yml with traefik setup?

**Comment by engineeringsys** [comment]
@DANW999 If you do a quick search there's quite a few utilities online to generate valid Vapid keys

**Comment by Xynnix** [comment]
I’m sure this has been said or done, if not, **try checking the browsers web console** if you haven’t. if it’s a proxy issue, I made a PR for those who wish to use NGINX as an easier proxy since it would just need editing/adding of nginx.conf and a proxy through cloud-flare for ssl.

**Comment by DANW999** [comment]
> The default configuration is intended for your local machine only, you have to configure the endpoints for it to work outside of your local machine.

That does not sound right. Docker port forwards exposed ports by default, unless I am missing something here?

**Comment by DANW999** [comment]
> @DANW999 If you do a quick search there's quite a few utilities online to generate valid Vapid keys. Or in the .env-example file there's a [link](https://github.com/revoltchat/self-hosted/blob/03437cf515c6a6fc4760007b2c7eab9fea696f5d/.env.example#L66)

Right thanks. I have left everything as default at the moment as I wish to test it first before making custom configurations.

**Comment by insertish** [comment]
In an effort to clean up the global issue tracker, I'm currently consolidating all issues regarding self-hosting into https://github.com/revoltchat/self-hosted/issues/25#issuecomment-1113606628.
