### ISSUE TITLE
bug: no invite code for server

### ISSUE THREAD

**Issue by akamuraaa** [revoltchat/self-hosted#83]
### What happened?

What happened?
- clicked on "create invite"
- got a blank invite
![Bild](https://github.com/revoltchat/self-hosted/assets/104314814/6f379f05-3b96-4d9f-9042-ca639ba2b9aa)

What did you expect to happen?
- it should have a code
- also the link should have the code, but it is "my.domain/invite/undefined"

**Comment by rhld16** [comment]
There seems to be a bug since the refactor in which the response to invite creation returns the wrong format.

Workaround: for now use the 20240212-1 image tag for the api container

**Comment by akamuraaa** [comment]
it worked, thanks.

**Comment by Rexogamer** [comment]
this has been fixed in the latest build - a migration should update any invites using the broken format. apologies for this!
