### ISSUE TITLE
bug: Rust Panic from failed migration

### ISSUE THREAD

**Issue by MetaverseRPN** [revoltchat/self-hosted#84]
### What happened?

After attempting to bring up revolt on the latest delta and bonfire versions, the client gives a network error with the following info showing up in the web console:
![image](https://github.com/revoltchat/self-hosted/assets/7560033/4bf922a0-7bd8-489c-bf51-e51821bb7da9)
Upon looking at the logs in portainer(as was setup in this guide here: https://gist.github.com/zicklag/c5adbf9bf4c5adb7640ed3e752c9eb28), the docker container for the API server appears to be shutting itself off with an exit code of 105, while constantly spamming the logs with this error:
`thread 'main' panicked at 'failed to insert corrected invite: Error { kind: InvalidArgument { message: "No documents provided to insert_many" }, labels: {}, wire_version: None, source: None }', crates/core/database/src/models/admin_migrations/ops/mongodb/scripts.rs:1058:14`
Any ideas what might be causing this?
I have followed all 3 important steps in the read me, including mounting Revolt.toml and this issue continues to persist despite this.

**Comment by insertish** [comment]
Just pushed a fix under https://github.com/revoltchat/backend/releases/tag/20240604-1, should be built within 30 minutes.

**Comment by insertish** [comment]
Pull and run latest images, please re-open if issue persists.
