### ISSUE TITLE
[Docs] Both initial FAQ links in the Readme 404

### ISSUE THREAD

**Issue by chocmake** [revoltchat/self-hosted#85]
### What happened?

Just a heads-up. These two links 404:

> Please [read the FAQ before running your own server](https://developers.revolt.chat/faq/usage#guidelines-for-third-party-instances) and you may want to read about [additional notes relating to third-party instances](https://developers.revolt.chat/faq/instances).

Not sure if the first link is now meant to be [this](https://support.revolt.chat/kb/safety/discover-guidelines) or something else.

(Sorry, there didn't seem to be a more relevant new issue template type, so not actually a bug)

**Comment by insertish** [comment]
fixed the links
