### ISSUE TITLE
bug: Revolt.toml requires two additional fields under smtp

### ISSUE THREAD

**Issue by dollhaus** [revoltchat/self-hosted#89]
https://github.com/revoltchat/backend/blob/main/crates/core/config/Revolt.toml

```
[api.smtp]
host = "" # do NOT put a port number here, it will not be recognised
username = ""
password = ""
from_address = ""
port = ""
use_tls = true #set to false where host is an IP address 
```

Note for future documentation: TLS will not function correctly over docker's host adaptor. If SMTP is running on the same machine, and is accessed via 172.17.0.1, the SMTP server should be configured to listen **only** on the docker interface.

**Comment by insertish** [comment]
I've added (as comments) the additional optional fields to avoid confusion.
