### ISSUE TITLE
Adding an admin user to get started

### ISSUE THREAD

**Issue by engineeringsys** [revoltchat/self-hosted#9]
Perhaps I'm overlooking something but I'm wanting to launch my own system to help with testing and contribution.  What is the default admin login?  Or how do I manually create a user for testing the system?

Thanks!

**Comment by engineeringsys** [comment]
Thank you, this worked.  However I'm receiving `Failed to register! · Network error.` from the UI when trying to create the account.  This is on a local docker host, no reverse proxy and non public-

**Comment by engineeringsys** [comment]
Disregard this one, I had another container taking 8000.

**Comment by TimothyRatliff** [comment]
How did you end up registering an account? I'm still getting `Failed to register! · Network error.` when trying to create an account. I don't have anything taking port 8000.
