### ISSUE TITLE
bug: NETWORKERROR on fresh install using non-standard port

### ISSUE THREAD

**Issue by Velikyi** [revoltchat/self-hosted#94]
### What happened?

On a fresh install on W11, without touching anything and using local, everything seems to work. When I try to follow the documentation for non-standard port by changing 80:80 to 1234:80, and changing caddy hostname to :80, and then try creating a new user or logging in with the previously made user, it returns NETWORKERROR. I noticed the documentation telling me to check the config before posting issue, but to my knowledge I'm doing exactly what the documentation says, so I don't understand what I'm supposed to check or do differently. Any help?

**Comment by Velikyi** [comment]
Tried this on macOS 13.5.2 on Apple M1 Pro as well, exact same error. Strangely, except I can't get this one to open locally on port 80 with standard config, even though there is nothing else running on port 80, but when doing the non-standard port config, the same happens as on W11

**Comment by pingdoug** [comment]
Fresh install following the Quick Start on a Docker Ubuntu 22.04 digital ocean droplet. I get NETWORKERROR. Here is my .env obviously swapping out mydomain.

```# Hostname used for Caddy
# This should in most cases match REVOLT_APP_URL
HOSTNAME=mydomain.com

# URL to where the Revolt app is publicly accessible
REVOLT_APP_URL=https://mydomain.com

# URL to where the API is publicly accessible
REVOLT_PUBLIC_URL=https://mydomain.com/api
VITE_API_URL=https://mydomain.com/api

# URL to where the WebSocket server is publicly accessible
REVOLT_EXTERNAL_WS_URL=wss://mydomain.com/ws

# URL to where Autumn is publicly available
AUTUMN_PUBLIC_URL=https://mydomain.com/autumn

# URL to where January is publicly available
JANUARY_PUBLIC_URL=https://mydomain.com/january```

**Comment by puffin-000** [comment]
I get the same error, I do as the documentation showed how to do. My country blocked Discord, I want to migrate to Revolt but this issue is stepping me back.

**Comment by insertish** [comment]
Closing due to stale, guide has been updated, please feedback if anything has improved/it's still the same.
